//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
[System.Serializable]
[CSVFilename("TestAction")]
[CSVDataAsset("TestActionDataTable")]
public class TestActionDataEntry : CSVDataUtility.IDataEntry{
            
	[CSVField("id")]
	public string id;

	[CSVField("actiontest")]
	public CSVDataUtility.Action.ActionInfo actiontest;

    [System.NonSerialized]
    public static System.Action<string, int> actiontest_action_tac1 = delegate { };

    [System.NonSerialized]
    public static System.Action<float> actiontest_action_tac2 = delegate { };

    public void Invoke_actiontest()
    {
        int paramIndex = 0;

        for (int i = 0; i < actiontest.callList.Count; i++)
        {
            switch (actiontest.callList[i])
            {
                
                case 0:
                    actiontest_action_tac1.Invoke((string)actiontest.paramList[paramIndex + 0].Value, (int)actiontest.paramList[paramIndex + 1].Value);
                    paramIndex += 2;
                    break; 

                case 1:
                    actiontest_action_tac2.Invoke((float)actiontest.paramList[paramIndex + 0].Value);
                    paramIndex += 1;
                    break; 

            }
        }
    }



    public string internal_dataEntryID { 
        get {
            return id;    
        } 
    }
    
    [CSVInternalIndex]
    public int m_internal_dataEntryIndex;
    public int internal_dataEntryIndex { get { return m_internal_dataEntryIndex; } }
}



[System.Serializable]
public class TestActionDataTable : CSVDataUtility.DataTable<TestActionDataEntry>{
    public static TestActionDataTable Create(){
        TestActionDataTable datatable = new TestActionDataTable();
        datatable.Read();
        return datatable;
    }
}

