//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
[System.Serializable]
[CSVFilename("TestStruct")]
[CSVDataAsset("TestStructDataTable")]
public class TestStructDataEntry : CSVDataUtility.IDataEntry{
            
	[CSVField("id")]
	public string id;

	[CSVField("person info")]
	public person_info_struct person_info;

    [System.Serializable]
    public struct person_info_struct
    {
		public string city;
		public int age;
		public float height;

    }

	[CSVField("education")]
	public List<education_struct> education;

    [System.Serializable]
    public struct education_struct
    {
		public int year;
		public string school;

    }



    public string internal_dataEntryID { 
        get {
            return id;    
        } 
    }
    
    [CSVInternalIndex]
    public int m_internal_dataEntryIndex;
    public int internal_dataEntryIndex { get { return m_internal_dataEntryIndex; } }
}



[System.Serializable]
public class TestStructDataTable : CSVDataUtility.DataTable<TestStructDataEntry>{
    public static TestStructDataTable Create(){
        TestStructDataTable datatable = new TestStructDataTable();
        datatable.Read();
        return datatable;
    }
}

