//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using UnityEngine;
using UnityEditor;

public class TestRefDataTable_AssetEditor
{
    [MenuItem("Assets/CSV Data Utility/DataAsset/Create TestRefDataTable")]
    public static void CreateAsset()
    {
        var asset = ScriptableObject.CreateInstance<TestRefDataTable_Asset>();
        CSVDataUtility.DataAssetUtility.ReadAsset(asset);
    }
}