//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[CSVDataAsset("TestRefDataTable")]
public class TestRefDataTable_Asset : CSVDataUtility.DataAsset<TestRefDataEntry>
{

}
