//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSVDataUtility.ClassWriter.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[CSVDataAsset("TestActionDataTable")]
public class TestActionDataTable_Asset : CSVDataUtility.DataAsset<TestActionDataEntry>
{

}
